Fix/checkbox and datepicker
digipolisantwerp/antwerp-ui_react pull request #251
Opened 2021-08-13 09:21 UTC by jsebrech

## PR Checklist

This PR fulfills the following requirements:

- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)
- [x] A changelog entry has been added to CHANGELOG.md if necessary

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] react application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #246 #247 #248 #249 

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

Dependencies were cleaned up and some were moved to peer dependencies. Should not be a breaking change, because no new dependencies were added.

## Other information

## Resolved issues

Fixes: #246
Fixes: #247
Fixes: #248
Fixes: #249

2021-08-23 16:18 UTC, TriangleJuice requested changes
Merci, Joeri! Ziet er al goed uit. Nog enkele kleine dingetjes voor na je vakantie.

2021-08-23 16:18 UTC, TriangleJuice commented on packages/form/src/Checkbox/Checkbox.js
> +  defaultId = 'aui-cb-' + Math.random().toString(36);
Misschien beter met [defaultProps](https://reactjs.org/docs/typechecking-with-proptypes.html#default-prop-values) werken hier?

2021-08-23 16:18 UTC, TriangleJuice commented on packages/form/src/Datepicker/Datepicker.js
> +  defaultId = 'aui-date-' + Math.random().toString(36);
Zelfde comment als hierboven.

2021-08-23 16:18 UTC, TriangleJuice commented on packages/form/src/Datepicker/Datepicker.spec.js
> +		const datepicker = shallow(<Datepicker qa="id-1234" id="id-4321" />);
Zelfde vraag als hierboven.

2021-08-23 16:18 UTC, TriangleJuice commented on packages/hero/src/Hero.spec.js
> +describe('Hero', () => {
Thanks for the first test 👍

2021-09-01 06:03 UTC, vademo approved these changes
Paar goede opmerkingen van @TriangleJuice maar ziet er voor de rest goed uit. 
excuses voor de late review

2021-09-01 09:08 UTC, jsebrech commented on packages/form/src/Checkbox/Checkbox.spec.js
> +      const component = shallow(<Checkbox qa="id-1234" id="id-4321" />);
dit gaf een code coverage verbetering

2021-09-01 09:09 UTC, jsebrech commented on packages/form/src/Checkbox/Checkbox.js
> +  defaultId = 'aui-cb-' + Math.random().toString(36);
Defaultprops zijn per-component ipv per-instance. Een id moet uniek zijn per instance.

2021-09-01 09:09 UTC, jsebrech commented on packages/form/src/Datepicker/Datepicker.js
> +  defaultId = 'aui-date-' + Math.random().toString(36);
Zelfde antwoord als hierboven :)

2021-09-01 09:09 UTC, jsebrech commented on packages/form/src/Datepicker/Datepicker.spec.js
> +		const datepicker = shallow(<Datepicker qa="id-1234" id="id-4321" />);
Zelfde antwoord als hierboven :)

2021-09-01 09:24 UTC, TriangleJuice approved these changes

2021-09-01 09:25 UTC, merged