Feature/table
digipolisantwerp/antwerp-ui_react pull request #269
Opened 2022-01-10 07:13 UTC by HybridFox

## PR Checklist

This PR fulfills the following requirements:

- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)
- [x] A changelog entry has been added to CHANGELOG.md if necessary

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] react application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

## Resolved issues

2022-01-14 11:25 UTC, jsebrech requested changes
over het algemeen thumbs up. hier en daar nog enkele kleine nitpicks.

2022-01-14 11:25 UTC, jsebrech commented on packages/table/src/components/Filter/Filter.js
> +        {!disableColumnSorting && (
misschien dat hier nog extra controls toegevoegd zouden moeten kunnen worden door de gebruiker van de table component? in de smart table staat hier bvb ook nog een exportknop

2022-01-14 11:56 UTC, HybridFox commented on packages/table/src/Table.js
> +    display?: 'generic',
Ben niet mee wat de toegevoegde waarde zou kunnen zijn voor "visible" maar akkoord met optional nog toe te voegen :)

2022-01-14 17:03 UTC, TriangleJuice requested changes
Zelfde (positieve) opmerking als Joeri: Great work! Ook nog wat nitpicks toegevoegd. Ook zeker erop letten dat je geen WCAG incompliant features toevoegt.

2022-01-14 17:03 UTC, TriangleJuice commented on packages/table/src/constants/Table.constants.js
> +export const DEFAULT_PAGINATION_OPTIONS = [
Kan je hier de defaults van Angular overnemen a.u.b.?

2022-01-17 07:30 UTC, HybridFox commented on package.json
> +    "build": "lerna exec --sort -- rollup -c",
Sommige packages dependen op elkaar, dit zorgt ervoor dat de packages in de juiste volgende gebuild worden

2022-01-17 07:31 UTC, HybridFox commented on packages/table/src/Table.js
> +          onClick={() => onRowClick(row)}
Ik zal het er uit halen, want dat steekt eigenlijk ook niet in de angular versie.

2022-01-17 07:32 UTC, HybridFox commented on packages/table/src/Table.js
> +  ofMessage: string,
Goed idee :)

2022-01-17 07:37 UTC, HybridFox commented on packages/table/src/Table.scss
> +	border-bottom: 1px solid #949494;
Was een foutje, heb het weggehaald :)

2022-01-17 07:40 UTC, HybridFox commented on packages/table/src/components/Filter/Filter.js
> +          <TelephoneNumber
Ik heb gewoon een paar form components toegevoegd die leken gebruikt te kunnen worden :)

2022-01-17 14:51 UTC, TriangleJuice approved these changes

2022-01-19 13:36 UTC, merged